# Pie Chart Stroke and Spacers

The `stroke` and the `color` aesthetics respectively set **line width** and **line color** of the pie sector arcs. 

The `strokeSide` parameter - "inner", "outer"(def), "both" - specifies where to show the arc.

By default `stroke` is 0, thus no arc is shown regardless of the value of `strokeSide` parameter.

Parameters `spacerWidth` and `spacerColor` define lines between sectors.
The default is a narrow segment of the same color as the plot background.

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.13.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.9.0.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
val mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg.csv")
mpg.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

In [4]:
letsPlot(mpg.toMap()) +
    geomPie(size = 20) {
        fill = "class"
    } +
    themeVoid()

#### 1. `stroke` and `color`

In [5]:
val palettes = scaleFillBrewer(palette = "Pastel2") +
    scaleColorBrewer(palette = "Set2")

In [6]:
letsPlot(mpg.toMap()) +
    geomPie(size = 20, stroke = 7) {
        fill = "class"
        color = "class"
    } +
    palettes +
    themeVoid()

#### 2. `strokeSide`

Note: `stroke=7` is added to parameters in order to make arks visible.

In [7]:
val p = letsPlot(mpg.toMap()) {
    fill = "class"
    color = "class"
} + palettes + themeVoid()

gggrid(listOf(
  p + geomPie(hole = 0.3, stroke = 7) + ggtitle("Inner & outer stroke (Default)"),
  p + geomPie(hole = 0.3, stroke = 7, strokeSide = "inner") + ggtitle("Inner stroke"),
  p + geomPie(hole = 0.3, stroke = 7, strokeSide = "outer") + ggtitle("Outer stroke")
)) + ggsize(1000, 300)

#### 3. `spacerWidth` and  `spacerColor`

"Spacer" is a thin line separating the pie' slices.\
You can adjust width and color of spacers.

In [8]:
letsPlot(mpg.toMap()) +
    geomPie(size = 20, hole = 0.3, spacerWidth = 4, spacerColor = "light-gray") {
        fill = "class"
    } +
    themeVoid()

##### 3.1 Spacers with Exploded Sectors 

Spacers are not shown for exploded sectors.

In [9]:
val mpg2 = mpg.add("explode") { if(`class` == "pickup") 0.2 else 0.0 }
mpg2.head(2)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,explode
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact,0.000000
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact,0.000000

In [10]:
letsPlot(mpg2.toMap()) +
    geomPie(size = 20, hole = 0.3,
            stroke = 2, color = "black",
            strokeSide = "both",
            spacerWidth = 4, spacerColor = "light-gray") {
        fill = "class"
        explode = "explode"
    } +
    themeVoid()